management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: always
      
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7010/discovery/eureka
      
spring:
  datasource:
    username: java
    password: java123
    driverClassName: org.postgresql.Driver
    tomcat:
      maxWait: 20000
      maxActive: 50
      maxIdle: 20
      minIdle: 15
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddlAuto: none