management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: always
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7010/discovery/eureka
