server:
  port: 5010
  servlet:
    contextPath: /uaa
spring:
  #database config
  datasource:
    url: jdbc:postgresql://localhost:5432/uaa_db
  #liquibase config
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/db.changelog-master.xml
check:
  user:
    scopes: true

  
