server:
  port: 5020
  servlet:
    contextPath: /company
spring:
  #database config
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
  #liquibase config
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/db.changelog-master.xml

  
